name: CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: yourusername/kodelab
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=branch
          type=sha,format=short
    
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.frontend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=yourusername/kodelab:buildcache-frontend
        cache-to: type=registry,ref=yourusername/kodelab:buildcache-frontend,mode=max
    
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}-backend
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=yourusername/kodelab:buildcache-backend
        cache-to: type=registry,ref=yourusername/kodelab:buildcache-backend,mode=max
  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    
    - name: Copy docker-compose file
      run: |
        scp docker-compose.prod.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/opt/kodelab/docker-compose.yml
    
    - name: Copy nginx config
      run: |
        scp -r nginx ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/opt/kodelab/
    
    - name: Deploy
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd /opt/kodelab && \
        echo 'SUPABASE_URL=${{ secrets.SUPABASE_URL }}' > .env && \
        echo 'SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}' >> .env && \
        echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> .env && \
        docker-compose pull && \
        docker-compose up -d"
